### ISSUE TITLE
how can i do to avoid "unchanged sprite revision on compas watch"? 

### ISSUE THREAD

**Issue by infinitystylish** [pierreburel/compass-hdpi#8]
When i compile my sass, it takes so much time compiling because the constant unchanged sprites revision, how can i avoid this behavior?

**Comment by pierreburel** [comment]
Hi,

isn't that more a Compass-related problem? This plugin is just using the existing Compass API to simplify the use of two different sprites map, that's all.
Maybe you should look there : https://github.com/Compass/compass/issues/897

Actually, I stopped using Compass (which I was using just for sprites and prefixing) because it was really slow and replaced it with Autoprefixer and Grunt/Gulp tasks for generating sprites (with .scss) :
 
* https://github.com/postcss/autoprefixer (https://github.com/ai/autoprefixer-rails) ;
* https://github.com/Ensighten/grunt-spritesmith#retina-parameters
